### ISSUE TITLE
Feature request: lightbox switch between images

### ISSUE THREAD

**Issue by michaelbecken** [lllychen/fry#1]
Hi Lily!

I am a jekyll newbie and tried to find a solution to move from image to image while in lightbox (let's say for example with left and right arrow), however I can not find a good way. It would be very nice if you could implement that feature.

Thank you!

**Comment by lilykonings** [comment]
Apologies for the late reply. Unfortunately, this project is becoming stale and I don't expect many updates in the near future. If I ever do revisit it, I'll be sure to take a look at this request.
